import { motion } from "framer-motion";
import { FiCheck, FiClock, FiMapPin, FiRefreshCw } from "react-icons/fi";

const statuses = ["Preparing", "Ready", "Out for delivery", "Delivered"];

export default function Orders() {
  const order = { number: "CH-48291376", date: "Today, 10:42 AM", total: "$24.36", items: "Velvet Latte, Sunrise Mocha", current: 1 };
  return <main className="min-h-screen bg-[#fffaf6] px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#b2763f]">Your account</p><h1 className="mt-3 text-4xl font-black text-[#2a1d17]">Orders & tracking</h1><p className="mt-3 text-[#725d51]">Follow every cup from our bar to your door.</p><motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mt-8 rounded-3xl bg-[#2a1d17] p-6 text-white shadow-[0_25px_60px_rgba(42,29,23,0.16)] sm:p-8"><div className="flex flex-wrap justify-between gap-4"><div><span className="text-xs uppercase tracking-wider text-[#d8c5b6]">Active order</span><h2 className="mt-2 text-2xl font-black">#{order.number}</h2><p className="mt-1 text-sm text-[#d8c5b6]">{order.items} · {order.total}</p></div><div className="flex items-center gap-2 rounded-full bg-[#e8bd88] px-4 py-2 text-sm font-bold text-[#2a1d17]"><FiClock /> 25–35 min</div></div><div className="mt-10 grid gap-5 sm:grid-cols-4">{statuses.map((status, index) => <div key={status} className="relative flex items-center gap-3 sm:block sm:text-center"><div className={`mx-0 flex h-10 w-10 items-center justify-center rounded-full sm:mx-auto ${index <= order.current ? "bg-[#e8bd88] text-[#2a1d17]" : "border border-white/20 text-white/50"}`}>{index <= order.current ? <FiCheck /> : index + 1}</div><span className={`mt-3 block text-sm font-semibold ${index <= order.current ? "text-white" : "text-white/40"}`}>{status}</span>{index < 3 && <div className={`hidden h-px sm:absolute sm:left-1/2 sm:top-5 sm:block sm:w-full ${index < order.current ? "bg-[#e8bd88]" : "bg-white/15"}`} />}</div>)}</div></motion.section><section className="mt-8 rounded-3xl border border-[#eadfd6] bg-white p-6 shadow-[0_18px_40px_rgba(73,44,31,0.05)]"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-black text-[#2a1d17]">Order history</h2><p className="mt-1 text-sm text-[#8a6a5e]">{order.date}</p></div><button className="flex items-center gap-2 rounded-full border border-[#e6d6c8] px-4 py-2 text-sm font-bold text-[#5c4033]"><FiRefreshCw /> Reorder</button></div><div className="mt-5 flex items-center gap-3 border-t border-[#f0e7df] pt-5 text-sm text-[#725d51]"><FiMapPin className="text-[#b2763f]" /> Delivering to your saved address</div></section></div></main>;
}
